version: "3.5"
services:
  ProductOwner.Microservice:
    image: ${DOCKER_REGISTRY-}item:v1
    build:
      context: ./item
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Host=192.168.2.1;Port=5432;Database=itemConnection ;User ID=postgres;Password=Test@123
      - RABBIT_MQ_SERVER=192.168.2.1
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBITMQSETTINGS__EXCHANGENAME=OfferExchange
      - RABBITMQSETTINGS__EXCHHANGETYPE=direct
      - RABBITMQSETTINGS__QUEUENAME=offer_queue
      - RABBITMQSETTINGS__ROUTEKEY=offer_route
    ports:
      - "4201:80"
  ProductUser.Microservice:
    image: ${DOCKER_REGISTRY-}repoitem:v1
    build:
      context: ./repoitem
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Host=192.168.2.1;Port=5432;Database=repoitemConnection ;User ID=postgres;Password=Test@123
      - RABBIT_MQ_SERVER=192.168.2.1
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBITMQSETTINGS__EXCHANGENAME=OfferExchange
      - RABBITMQSETTINGS__EXCHHANGETYPE=direct
      - RABBITMQSETTINGS__QUEUENAME=offer_queue
      - RABBITMQSETTINGS__ROUTEKEY=offer_route
    ports:
      - "4202:80"
